### ISSUE TITLE
Twisted Edge Snowboarding bad graphics

### ISSUE THREAD

**Issue by loganmc10** [cxd4/rsp#10]
![te](https://cloud.githubusercontent.com/assets/848146/26558977/d1df605c-4469-11e7-830c-41072a6ef0f0.png)

This is using GLideN64. It looks normal using Project64's RSP. The same thing happens on mupen64plus. Looks normal using rsp-hle, but looks like this using rsp-cxd4.

**Comment by loganmc10** [comment]
Actually this is probably just a case of GLideN64 failing at LLE, if I set "DisplayListToGraphicsPlugin" then it looks fine.

I'll see myself out...

**Comment by cxd4** [comment]
Without having time to check it out now, I'm fairly sure it's a legitimate find if you have the issue with LLE and only with one RSP plugin.  With that having been said, I'll have to confirm it tomorrow.

What version or commit was your build of my RSP plugin done from?  Also, as I'm not really acquainted with _1080 Snowboarding_, is there anything I should know about reaching where you got the glitch?

**Comment by cxd4** [comment]
>if I set "DisplayListToGraphicsPlugin" then it looks fine.

Hmm that makes it sound like a pretty old version if it has that INI-like config file model for setting that.

I would run `./make.sh` to build the plugin from the latest commit, then most likely that issue is fixed.

**Comment by loganmc10** [comment]
The other RSP I tried was HLE, not LLE. I didn't try the Project64 RSP in LLE mode

This is the very beginning of the first race if you just press A through all the menu options. But I'm almost certain it's just a GLideN64 bug.

I tested mupen64plus-rsp-cxd4, which is up to date with this repo, it has the "DisplayListToGraphicsPlugin" option. I can't remember where I got the Project64 compatible copy, it says version 0.1.1 I believe

**Comment by cxd4** [comment]
If you didn't try the LLE mode of the other RSP then the result of LLE has no comparison here.

In that case I think you're correct since it looks fine with z64gl.  This sort of ambiguity might be preventable by having other LLE plugins besides GlideN64 to test with on Mupen64Plus.
