### ISSUE TITLE
SupportCPUSemaphoreLock LLE only

### ISSUE THREAD

**Issue by loganmc10** [cxd4/rsp#11]
I recently discovered that ```NBA Showtime - NBA on NBC``` requires ```SupportCPUSemaphoreLock``` to boot. I tested mupen64plus, I haven't tested Project64 yet.

Because of these lines:
https://github.com/cxd4/rsp/blob/master/su.c#L60-L61

It only works in LLE graphics mode. But I commented out those lines, and the game works in HLE, still requiring ```SupportCPUSemaphoreLock```.

Can those lines be removed? Why is it currently only available in LLE?

**Comment by cxd4** [comment]
I don't remember the discussion very well, but Mystical Ninja used the semaphore lock as well (without requiring this hack).  After all it is just a hack for the plugin system, not actual timing fixes.

Basically it has to do with how the plugin waits for the emulator's side of the hack to be done before returning.  When mixing HLE graphics/audio with LLE graphics/audio there was crashing in Project64 on Mystical Ninja.  An HLE task goes through entirely different procedures in the plugin system than an LLE task, so the most reliable stability with using the semaphore lock timing hack was with keeping consistent.

It is preferable, then, to consistently use LLE for both task types when maximizing accuracy.  I don't remember how many years ago the report was; maybe Mystical Ninja would no longer crash in current versions of Project64 if mixing HLE with LLE task emulation methods.

**Comment by cxd4** [comment]
If you do remove those two lines, does _NBA Showtime - NBA on NBC_ fail with HLE graphics and LLE audio, or--inversely-- does it fail with LLE graphics and HLE audio?

If the latter is the case, then I would simply recommend using LLE audio as well.  A different HLE audio implementation surely is modifiable to get the game compatible with or without some implementation of the semaphore's concept, but the performance lost from LLE graphics makes that benefit fairly negligible.

**Comment by loganmc10** [comment]
So LLE graphics + LLE audio work fine. HLE graphics + LLE audio also work fine (this is all using ```SupportCPUSemaphoreLock```). If I enable HLE audio it no longer boots (LLE and HLE graphics have the same issue).

I can test Project64 on Monday, but they have ```Audio Signal=Yes``` in their RDB, and they said that is required to get this game to boot for them. I'm not sure what it does.

**Comment by cxd4** [comment]
If there is no booting with HLE audio then that is different from the case I remember with _Mario no Photopi_ which wouldn't work without it being emulated in the graphics task.  The HLE code for _NBA Showtime_ may be able to use some hackaround.

Where is it said that `Audio Signal=Yes` is needed for this game?  That's normally just a messenger to get MusyX stuff working on the part of the Project64 core.

Just to be sure I'm understanding, HLE audio no longer boots = HLE audio + LLE graphics never boots and HLE audio + HLE graphics never boots, regardless of the value of `SupportCPUSemaphoreLock`?

**Comment by loganmc10** [comment]
Here is where I read that it needs the Audio Signal:
https://github.com/project64/project64/pull/258/commits/b6559e149242daaccc0b8510ac7bcb1c44abec20

Yeah the only thing that boots is LLE audio + ```SupportCPUSemaphoreLock``` + HLE or LLE graphics

**Comment by loganmc10** [comment]
I just tested this on Project64. I got rid of the "Audio Signal" setting, and tried setting ```SupportCPUSemaphoreLock```, but it wouldn't boot. It only seems to boot if that ```Audio Signal=Yes``` is set

**Comment by cxd4** [comment]
I guess it's stable for some games, but it would crash on Project64's implementation of the hack.

It really is best to just use full LLE if also trying to hack around the lack of cycle-accuracy with the semaphore hack, but if you want or need some sort of speed up from partial HLE and Mupen64's implementation of the hack isn't crashing at places where Project64's method of doing it is, then I say go for it.

I guess it's a moot point since my configuration utility (cxd4/spconfig) doesn't offer the ability to enable the CPU semaphore hack if either HLE graphics or audio was selected anyway, but you can always work around that with a hex editor or whatever now that I've removed the two lines as you asked.

https://github.com/cxd4/rsp/commit/b03a098b857a36d4c26161d8923fa29c2435ad6f

**Comment by loganmc10** [comment]
Awesome thanks!
