### ISSUE TITLE
vrcp and others 

### ISSUE THREAD

**Issue by olivieryuyu** [cxd4/rsp#12]
hello

I am still stuck with the vrcp and other kind of instructions.

I cannot figure out the way to do the calculation and very honestly I spend hours without success on it.

I am not a programmer, I have just some basic knowledge of MIPS asm.

So I have for instance VRCP 0x0035 = 0x4200 (PJ64 result).

How can I calculate this?

I cannot figure the maths here, I feel like completely dummy :(

A very simple explanation would be great.

thx

**Comment by cxd4** [comment]
How you choose to evaluate the reciprocal depends on where you place the radix point.

0035_16 = 0000 0000 0011 0101_2 = 53_10
4200_16 = 0100 0010 0000 0000_2 = 66_10 * 2^16

1/x = 66.0
x = 1/66.0

You would then convert (1.0 / 66.0) from decimal point representation to binary point FP.

Or, if you read it as 15.17 fixed-point format:
4200_16 >> 1 = 0100 0010 0000 0000_2 = 33_10 * 2^17

The radix point has to be read in with a binary number, so it's not like the usual "decimal point" in floating-point numbers you're used to working with from public math schooling.

At any rate, whether you make that determination is not really important.  As stated in the PJ64 copy of your issue, the RCP lacks the hardware to do real division or any sort of FP operation, just fixed-point, so the results are really just functions of smaller-precision scalars etched into ROM on the RCP.  You figuring out that "algorithm" (or lack thereof) isn't going to affect much; most of the time a dummy FP cast using 1 / (float)element writing just about any value back to the destination element is going to make no visually noticeable difference in the games, so you could easily oversimplify this instruction when doing your HLE.
