### ISSUE TITLE
VCH failing tests on real hardware

### ISSUE THREAD

**Issue by cxd4** [cxd4/rsp#18]
Continued discussion of the relevant, unsolved portion of https://github.com/cxd4/rsp/pull/15.

Implementation of high vector clip test selects in the RSP is failing certain parts of krom's (a.k.a. PeterLemon's) test ROMs.

Op-code results on a real N64:  https://raw.githubusercontent.com/PeterLemon/N64/master/RSPTest/CP2/VCL/RSPCP2VCL.png
Op-code results using my plugin:  https://n64.gitlab.io/cpu/rcp/rsp/vch-fail.gif

So it looks so far like just off-by-one errors as @Zapeth says.

Due to how hard it is to interpret the results from the images, I've made a chart:
```
  VS     VT   VD_N64 VD_EMU
------ ------ ------ ------
...
     0 -30567 +30567 +30566 # f(0x0000, -0x8899) should be 0x7767, not 0x7766.
     0 -21829 +21829 +21828 # f(0x0000, -0xAABB) should be 0x5545, not 0x5544.
     0 -13091 +13091 +13090 # f(0x0000, -0xCCDD) should be 0x3323, not 0x3322.
     0  -4353  +4353  +4352 # f(0x0000, -0xEEFF) should be 0x1101, not 0x1100.
...
   +17    -18    +18    +17 # f(+0x0011, -0xFFEE) should be +0x0012, not +0x0011.
 +8755  -8756  +8756  +8755 # f(+0x2233, -0xDDCC) should be +0x2234, not +0x2233.
+17493 -17494 +17494 +17493 # f(+0x4455, -0xBBAA) should be +0x4456, not +0x4455.
+26231 -26232 +26232 +26231 # f(+0x6677, -0x9988) should be +0x6678, not +0x6677.
-30567 +30566 -30566 -30567 # f(-0x8899, +0x7766) should be -0x889A, not -0x8899.
-21829 +21828 -21828 -21829 # f(-0xAABB, +0x5544) should be -0xAABC, not -0xAABB.
-13091 +13090 -13090 -13091 # f(-0xCCDD, +0x3322) should be -0xCCDE, not -0xCCDD.
 -4353  +4352  -4352  -4353 # f(-0xEEFF, +0x1100) should be -0xEF00, not -0xEEFF.
...
```

**Comment by LegendOfDragoon** [comment]
Based on a quick analysis, I believe the problem is related to the commit you made a while back, in order to fix the bug i mentioned to you. I guess I never double checked your code after you made the change and assumed it fixed everything without any regressions. https://github.com/cxd4/rsp/commit/c42ac84651f5cb2380dcd87e7c293809e0b2a954

**Comment by cxd4** [comment]
At first I couldn't believe you said that (because why would a commit designed to handle the corner case of VT == -32768 be responsible for multiple test fails outside that condition), but it seems extremely likely now that this is the commit to blame after all.  Commented as to why...really it doesn't make sense to use the sign flag or sn[] to decrement the difference, then "correct" the op-code by only doing it if VT is a corner-case value.  Highly likely I made a typo there.

That commit feels like forever ago.  What were you testing or reporting that caused me to make that commit?  Wrestlemania or some other thing perhaps?

**Comment by LegendOfDragoon** [comment]
The Wrestlemania thing was prior to that. At that point, I was doing my own implementation for many of the vector instructions and wanted to make sure that my new code matched 100% with the docs. I used to run loops and tested all possible inputs for the many of the vector instructions. Iirc, your code prior to that commit for VCH matched all but 1 case. It does feel like a very long time ago lol.

**Comment by cxd4** [comment]
>Iirc, your code prior to that commit for VCH matched all but 1 case.

It's hard to believe otherwise, as the commit in question was a fix to the fact that -1:-32767 all have positive counterparts, but -32768 doesn't in a 16-bit slice.  I probably didn't truly need to take the absolute value of anything, but all the comparisons in VCH just warranted sign-flipping for speed reasons.

The fact that this commit fixed a prior situation in which only a single case was broken and caused a situation in which numerous cases are mildly and slightly broken seems to be proof that I should just go ahead and make the change from sn[i] to ~sn[i].
