### ISSUE TITLE
VMADL, VMADM ... Help please

### ISSUE THREAD

**Issue by olivieryuyu** [cxd4/rsp#9]
I am currently trying to reverse ucodes for HLE development (currently Rogue Squadron, not easy at all).

I have now a good knowledge of SU mips and easy VU mips inctructions but I am lost with VU multiplication, division and so on.

If you could help out to understand how it works to, would be nice from you.

Here an example:

![image](https://cloud.githubusercontent.com/assets/8987490/24764227/f7b0d7ec-1af3-11e7-9a96-b75d250fa030.png)

What is v2 [0h]? and how to interpret the command?

This is V2 and V4

![image](https://cloud.githubusercontent.com/assets/8987490/24764372/6ffe4874-1af4-11e7-9357-119c299a79b6.png)

and the results in Jabo RSP:

![image](https://cloud.githubusercontent.com/assets/8987490/24764327/417b7f6c-1af4-11e7-9107-a894b15ff4c8.png)

I am lost, how do i get there???

**Comment by cxd4** [comment]
VR[6] += VR[3] * VR[2] ... so $v4 isn't part of the equation there.  I would compare $v6.

The [0h] is just an optional specifier to broadcast single scalar coefficient factors against $v3 rather than corresponding the vector multiplication on the standard element-to-element matchup.

**Comment by olivieryuyu** [comment]
Thanks! I understand now but still struggling a lot to interpret that in a more "HLE" manner.

There is some specific format in the N64 programming manual as for instance S10.5. Is there a relationship between format and type of multiplication made in the RSP? Would u have an idea?

For instance I am working on a specific part of the vertex command of Rogue Squadron for fog.

![image](https://cloud.githubusercontent.com/assets/8987490/25402258/7487d73a-29f8-11e7-91b6-5449d7902222.png)

For this case, I would understand that we would do a 32 bits addition.

And for this case:

![image](https://cloud.githubusercontent.com/assets/8987490/25402286/89a72710-29f8-11e7-8138-b6648b4a5f83.png)

a 32 bits multiplication.

Do i stand correct?

**Comment by cxd4** [comment]
VMUL[F/U/Q/I] is single-precision multiplication.
VMUD[L/M/N/H] is double-precision multiplication.
VMAC[F/U/Q/I] is single-precision accumulative multiplication.
VMAD[L/M/N/H] is double-precision accumulative multiplication.

Double-precision multiplication adds the product to a previous 32-bit designation within one of the 8 48-bit accumulator elements.  Whether the element being stored is within the high (H), middle (M/N), or low (L) segment with respect to the 48-bit source is defined by L/M/N/H, with additional alterations of zero- or sign-extended interpretation of the bit-wise source and target numbers to account for negative or whole-number-only modes of arithmetic (the inversion of which being signed and unsigned being the distinction between M and N for middle).

Multiply-and-add just means that it reads from what was already in each accumulator element and just adds the product to that.  Standard multiply disregards the existing accumulator value and just redefines it.  Single-precision multiply as well as multiply-and-add can be done with sign-extension (F) or zero-extension (U) fractional adjustments.

**Comment by olivieryuyu** [comment]
ok thanks!

I am learning little by little but I will ge there.
